
### Get Authenticated User Request
# @name authUser
POST  http://10.77.77.22:8080/api/exams
Content-Type: application/json
Accept: application/json

{
  "exam_title": "Health Care Introduction Exam",
  "max_exam_can_take": 2,
  "active": true
}
