
### Get Authenticated User Request
# @name authUser
POST  http://localhost:8000/api/question-banks
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "question_text": "My Question",
  "question_section_id": 1,
  "active": true,
  "question_options": [
    {
        "id": 1,
        "question_bank_id": 1,
        "option_text": "Option One",
        "is_correct": true
    },
    {
        "id": 2,
        "question_bank_id": 1,
        "option_text": "Option Two",
        "is_correct": false
    },
    {
        "id": 3,
        "question_bank_id": 1,
        "option_text": "Option Three",
        "is_correct": false
    },
    {
        "id": 4,
        "question_bank_id": 1,
        "option_text": "Option Four",
        "is_correct": false
    }
  ]
}
