
### Get Authenticated User Request
# @name authUser
POST  http://localhost:8000/api/question-sections
Content-Type: application/json
Accept: application/json

{
  "section_title": "Section One",
  "question_for_section": 4,
  "time_for_section": 300000,
  "order": 1,
  "active": true
}
