
### Get Authenticated User Request
# @name authUser
POST  http://localhost:8000/api/answer-sheets
Content-Type: application/json
Accept: application/json

{
  "id": 1711348336958,
  "emp_code_exam_id_exam_num": "1180_1_1",
  "exam_id": 1,
  "name": "NEWTON MITRA",
  "employee_code": "1180",
  "exam_num": 1,
  "total_questions": 10,
  "correct_answers": 9,
  "wrong_answers": 1,
  "submitted_answers": [
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 7,
      "question_option_id": 26,
      "option_text": "৫০%",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 9,
      "question_option_id": 34,
      "option_text": "৬ মাস",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 13,
      "question_option_id": 49,
      "option_text": "২০০ টাকা                             ",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 14,
      "question_option_id": 53,
      "option_text": " ৭০%                                 ",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 15,
      "question_option_id": 59,
      "option_text": "৭৫ বছর                                 ",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 16,
      "question_option_id": 62,
      "option_text": "পনের লক্ষ টাকা ",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 17,
      "question_option_id": 65,
      "option_text": "৫০ টাকা                             ",
      "is_correct": 0
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 19,
      "question_option_id": 76,
      "option_text": " ৬ মাস",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 23,
      "question_option_id": 91,
      "option_text": "২০০ টাকা",
      "is_correct": 1
    },
    {
      "employee_code": "1180",
      "employee_exam_id": 1711348336958,
      "exam_id": 1,
      "question_bank_id": 26,
      "question_option_id": 103,
      "option_text": "৭৫ বছর",
      "is_correct": 1
    }
  ]
}